### ISSUE TITLE
Report write up milestone 1

### ISSUE THREAD

**Issue by MengLeZhang** [MengLeZhang/wardenProject2021#14]
- [x] evidence on studies quoting that these borders are apparent
- [x] complete project timeline
- [x] add completion times
- [x] add descriptives of the maps
- [x] check it actually read okay
- [x] add pictures of the maps

**Comment by MengLeZhang** [comment]
moved onto word and sent to coauthors
